defaults:
  - hydra: default
  - _self_

hydra:
  searchpath:
    - file://conf/

data_path_prefix: /mnt/fangkai_blob/share/
model_path_prefix: /mnt/fangkai_blob/share/models # ../pretrained-models/
output_path_prefix: /mnt/fangkai_blob/reward_modeling/

global_split_id: 0
train_file:
dev_file:
#test_file: ${model_path_prefix}/mathstral-7B-v0.1/mathscale4o/train.330k.v1.0.boxed.${global_split_id}-of-11.json
test_file: ${model_path_prefix}/mathstral-7B-v0.1/mathscale4o/train.500k.de_con.v1.0.boxed.${global_split_id}-of-20.json

port: 6000
model:

sampling_params:
  _target_: vllm.SamplingParams
  n: 10
  temperature: 1.0
  max_tokens: 4096
  stop: [ "<eos>", "\n\n\n\n", "### Instruction", "<｜end▁of▁sentence｜>", "</s>", "<pad>" ]
  top_p: 0.9

tem: ${sampling_params.temperature}
n: ${sampling_params.n}
top_p: ${sampling_params.top_p}
split_size: 64
split_id: 0
max_num_seqs: 64
max_model_len: 4096
global_batch_size: 512

suffix: ${split_id}-of-${split_size}
#output_file: ${output_dir}/${eval_sub_path}/mathscale4o/split-${global_split_id}-of-11/train.330k.boxed.v1.0.${global_split_id}-of-11.0shot.n${n}.tem${tem}.p${top_p}.${suffix}.json
output_file: ${output_dir}/${eval_sub_path}/mathscale4o/500k-split-${global_split_id}-of-20/train.500k.de_con.boxed.v1.0.${global_split_id}-of-20.0shot.n${n}.tem${tem}.p${top_p}.${suffix}.s${seed}.json
flush_file: ${output_file}l

apply_chat_template: False
add_generation_prompt: True

read_tensor:
  _target_: data.combine_dataset.ResponseAlignDataset
  template: "{question}\n\nPlease put your final answer within {instruction}."
  instruction: "\\boxed{}"
  split_size: ${split_size}
  split_id: ${split_id}
  service_based: False
  service_processor:
    _target_: data.vllm.VLLMRequestGenerator
    api_url: http://0.0.0.0:${port}/v1/completions
    max_tokens: ${sampling_params.max_tokens}
    model: ${model}
    stop: ${sampling_params.stop}
    n: ${n}
    temperature: ${tem}
    top_p: ${top_p}
#  index_field: uuid
  index_field: id
  flush_file: ${flush_file}


save_best: False
step:
exp_name:
exp_notes:
#output_dir: ${model_path_prefix}/mathstral-7B-v0.1/
output_dir: ${output_path_prefix}/experiments/${exp_name}/
eval_sub_path: ""

# Dataloader
num_workers: 8
prefetch_factor: 2

dp_size:
tp_size: 1
pp_size: 1


post_process:
  _target_: post_processors.openai_api_callback.MathScaleCallBack
  answer_clean:
  output_file: ${output_file}
  resume: True
#  index_field: "uuid"
  index_field: "id"
  label_field: "label"
#  saved_keys: [ "question", "uuid", "solution", "box_solution" ]
  saved_keys: ["question", "solution", "box_solution"]

# Training hyper-parameters
per_gpu_train_batch_size: 1
per_gpu_eval_batch_size: 1

ddp_eval: False
no_cuda: False
seed: 42
local_rank: -1

# Temporary variables
fp16: True
fp16_bfloat16: True
n_gpu: 1
device:
train_batch_size:
eval_batch_size:
world_size:
