defaults:
  - hydra: default
  - _self_

hydra:
  searchpath:
    - file://conf/

data_path_prefix: /mnt/fangkai_blob/share/
model_path_prefix: /mnt/fangkai_blob/share/models # ../pretrained-models/
output_path_prefix: /mnt/fangkai_blob/reward_modeling/

sample_over_p: 16

sft_model_dir: ${output_path_prefix}/experiments/mathstral.mathscale4o.sft.V100.tp2dp8.v2.0.s42/checkpoint-800/
global_split_id: 0
train_file:
dev_file:
#test_file: ${model_path_prefix}/mathstral-7B-v0.1/mathscale4o/split-0-of-11/train.330k.boxed.v1.0.0-of-11.0shot.n20.tem1.0.p0.9.upper0.7.r0.3.inter_step.json
#test_file: ${model_path_prefix}/mathstral-7B-v0.1/mathscale4o/split-0-of-11/train.330k.boxed.v1.0.0-of-11.0shot.n20.tem1.0.p0.9.upper0.7.r0.3.filter_same.json
#test_file: ${sft_model_dir}/mathscale4o/train.500k.de_con.boxed.v1.0.n10.tem1.0.p0.9.upper0.7.r0.3.sample${sample_over_p}.filter_same.${global_split_id}-of-4.json
test_file: ${sft_model_dir}/mathscale4o/mscale-v0.1-300k/mscale.v0.1.300k.v1.0.n10.tem1.0.p1.0.upper0.7.r0.3.sample10.filter_same.json

port: 6000
model:

sampling_params:
  _target_: vllm.SamplingParams
  n: 3
  temperature: 1.0
  max_tokens: 2048
  stop: [ "<eos>", "\n\n\n\n", "### Instruction", "<｜end▁of▁sentence｜>", "</s>", "<pad>" ]
  top_p: 0.9

tem: ${sampling_params.temperature}
n: ${sampling_params.n}
top_p: ${sampling_params.top_p}
split_size: 256
split_id: 0
max_num_seqs: 64
max_model_len: 2048
global_batch_size: 512

suffix: ${split_id}-of-${split_size}
#output_file: ${output_dir}/${eval_sub_path}/mathscale4o/split-${global_split_id}-of-11/train.330k.boxed.v1.0.${global_split_id}-of-11.n20.tem1.0.p0.9.upper0.7.r0.3.prefix_completion.n${n}.tem${tem}.p${top_p}.${suffix}.json
#output_file: ${output_dir}/${eval_sub_path}/mathscale4o/split-${global_split_id}-of-11/train.330k.boxed.v1.0.${global_split_id}-of-11.n20.tem1.0.p0.9.upper0.7.r0.3.filter_same.prefix_completion.n${n}.tem${tem}.p${top_p}.${suffix}.json
#output_file: ${sft_model_dir}/mathscale4o/split-${split_size}/train.500k.de_con.boxed.v1.0.n10.tem1.0.p0.9.upper0.7.r0.3.sample${sample_over_p}.filter_same.${global_split_id}-of-4.prefix_completion.n${n}.tem${tem}.p${top_p}.${suffix}.json
output_file: ${sft_model_dir}/mathscale4o/mscale-v0.1-300k/split-${split_size}/mscale.v0.1.300k.v1.0.n10.tem1.0.p1.0.upper0.7.r0.3.sample10.filter_same.prefix_completion.n${n}.tem${tem}.p${top_p}.${suffix}.json
flush_file: ${output_file}l

apply_chat_template: False
add_generation_prompt: True

read_tensor:
  _target_: data.combine_dataset.ResponseAlignDataset
  aligner:
    _target_: data.input_aligner.concat_aligner
    aligners:
      - _target_: data.input_aligner.flat_aligner
        input_index_field: id
        extract_field: [ "prefix", "prefix_id" ]
        mode: "multi"
  template: "{question}\n\nPlease put your final answer within {instruction}.{prefix}"
  instruction: "\\boxed{}"
  split_size: ${split_size}
  split_id: ${split_id}
  service_based: False
  service_processor:
    _target_: data.vllm.VLLMRequestGenerator
    api_url: http://0.0.0.0:${port}/v1/completions
    max_tokens: ${sampling_params.max_tokens}
    model: ${model}
    stop: ${sampling_params.stop}
    n: ${n}
    temperature: ${tem}
    top_p: ${top_p}
  index_field: prefix_id
  flush_file: ${flush_file}


save_best: False
step:
exp_name:
exp_notes:
#output_dir: ${model_path_prefix}/mathstral-7B-v0.1/
output_dir: ${sft_model_dir}
eval_sub_path: ""

# Dataloader
num_workers: 8
prefetch_factor: 2

dp_size:
tp_size: 1
pp_size: 1


post_process:
  _target_: post_processors.openai_api_callback.MathScaleCallBack
  answer_clean:
  output_file: ${output_file}
  resume: True
  index_field: "prefix_id"
  label_field: "label"
#  saved_keys: [ 'question', 'uuid', 'solution', 'box_solution', 'prefix', 'prefix_id']
  saved_keys: [ 'question', 'id', 'prefix', 'prefix_id']

# Training hyper-parameters
per_gpu_train_batch_size: 1
per_gpu_eval_batch_size: 1

ddp_eval: False
no_cuda: False
seed: 42
local_rank: -1

# Temporary variables
fp16: True
fp16_bfloat16: True
n_gpu: 1
device:
train_batch_size:
eval_batch_size:
world_size:
