x-net: &default-net
  networks:
    - aic-net

x-restart: &default-restart
  restart: unless-stopped

services:
  # -------- Elasticsearch with Vietnamese plugin --------
  es-vi:
    build:
      context: ./elasticsearch-vi
      args:
        ES_VERSION: "8.7.0"   # Keep at 8.7.0 unless the plugin releases a newer build
    image: elasticsearch-vietnamese
    restart: on-failure
    container_name: es-vi
    environment:
      xpack.security.enabled: "false"
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xmx4g -Xms4g -Djava.library.path=/usr/lib:/usr/local/lib"
    ports:
      - "9200:9200"
    volumes:
      - ./data:/usr/share/elasticsearch/data

    networks:
      - aic-net

  # ----------------------- MongoDB -----------------------
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    # For local/dev, no auth (your app uses mongodb://localhost:27017)
    # Add MONGO_INITDB_ROOT_* envs if you want auth
    <<: [*default-net, *default-restart]

  # ----------------------- Milvus stack -----------------------
  etcd:
    image: quay.io/coreos/etcd:v3.5.18
    container_name: milvus-etcd
    command: >
      etcd -advertise-client-urls=http://etcd:2379
           -listen-client-urls=http://0.0.0.0:2379
           --data-dir /etcd
    volumes:
      - etcddata:/etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    <<: [*default-net, *default-restart]

  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    container_name: milvus-minio
    command: minio server /minio_data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    <<: [*default-net, *default-restart]

  milvus:
    image: milvusdb/milvus:v2.6.0
    container_name: milvus-standalone
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MQ_TYPE: woodpecker
    depends_on:
      - etcd
      - minio
    ports:
      - "19530:19530"  # gRPC
      - "9091:9091"    # REST/metrics
    volumes:
      - milvusdata:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    security_opt:
      - seccomp:unconfined
    <<: [*default-net, *default-restart]

networks:
  aic-net:
    driver: bridge

volumes:
  esdata:
  mongodata:
  etcddata:
  miniodata:
  milvusdata: